api:
  account_password: ""
  auto_login: true
  cert_password: ""
risk:
  max_daily_loss: 0.02
  max_daily_trades: 10
  max_position_ratio: 0.1
  stop_loss_pct: 0.03
  take_profit_pct: 0.07
trading:
  auto_trading: true
  ignore_market_time: false
  market_end_time: "15:30:00"
  market_start_time: 09:00:00
  strategies:
    - name: RSI_Strategy
      params:
        overbought: 70
        oversold: 30
        period: 14
  test_mode: true
  trading_mode: test
  universe:
    - 005930
    - "000660"
    - "035420"
